# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page3_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmTransferWindow(object):
    def setupUi(self, ConfirmTransferWindow):
        ConfirmTransferWindow.setObjectName("ConfirmTransferWindow")
        ConfirmTransferWindow.resize(535, 202)
        self.centralwidget = QtWidgets.QWidget(ConfirmTransferWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Confirm_Project_complete = QtWidgets.QLabel(self.centralwidget)
        self.Confirm_Project_complete.setGeometry(QtCore.QRect(30, 40, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Confirm_Project_complete.setFont(font)
        self.Confirm_Project_complete.setObjectName("Confirm_Project_complete")
        self.Confirm_Project_complete_2 = QtWidgets.QLabel(self.centralwidget)
        self.Confirm_Project_complete_2.setGeometry(QtCore.QRect(30, 80, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Confirm_Project_complete_2.setFont(font)
        self.Confirm_Project_complete_2.setObjectName("Confirm_Project_complete_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 140, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        ConfirmTransferWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConfirmTransferWindow)
        self.statusbar.setObjectName("statusbar")
        ConfirmTransferWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfirmTransferWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmTransferWindow)

    def retranslateUi(self, ConfirmTransferWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmTransferWindow.setWindowTitle(_translate("ConfirmTransferWindow", "Confirm Transfer Part to Spare"))
        self.label_4.setText(_translate("ConfirmTransferWindow", "EE WAREHOUSE CONTROLLER"))
        self.Confirm_Project_complete.setText(_translate("ConfirmTransferWindow", "Purchasing and Assembling Process completed?"))
        self.Confirm_Project_complete_2.setText(_translate("ConfirmTransferWindow", "Are you sure to transfer residual part to Spare Warehouse?"))
        self.pushButton.setText(_translate("ConfirmTransferWindow", "OK"))
        self.pushButton_2.setText(_translate("ConfirmTransferWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmTransferWindow = QtWidgets.QMainWindow()
    ui = Ui_ConfirmTransferWindow()
    ui.setupUi(ConfirmTransferWindow)
    ConfirmTransferWindow.show()
    sys.exit(app.exec_())
